DROP TABLE IF EXISTS contact;
CREATE TABLE contact (id INTEGER PRIMARY KEY, name VARCHAR(50) NOT NULL, phonenumber VARCHAR(50) NOT NULL);
CREATE TABLE users (id INTEGER PRIMARY KEY, name VARCHAR(50) NOT NULL, username VARCHAR(50) NOT NULL, password VARCHAR(50) NOT NULL);
CREATE TABLE roles (id INTEGER PRIMARY KEY, name VARCHAR(50) NOT NULL);